import Head from 'next/head';

import styles from 'styles/Error.module.css';

const NotFound = () => (
  <>
    <Head>
      <title>Planets Star Wars</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.div}>
      <h1>Page 404</h1>
    </div>
  </>
);

export default NotFound;
