import { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

const Home = () => {
  const router = useRouter()

  // useEffect(() => {
  //   router.push('/frontpage')
  // }, [])
  return (
  <Head>
    <title>Planets Star Wars</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)};

export default Home;
